### PR TITLE
Issue#278 bleu score lens

### LINKED ISSUE #278: BLEU score Lens to compare two rows in a column
**Is your feature request related to a problem? Please describe.**
It would be nice to have a Lens showing the per column BLEU score in the Inspector widget [create a new Lens](https://renumics.com/docs/development/lenses).

**Describe the solution you'd like**
An additional Lens should be added to the Inspector widget displaying the [BLEU score](https://en.wikipedia.org/wiki/BLEU) between two columns.

**Additional context**
[arxiv-summarization](https://huggingface.co/datasets/ccdv/arxiv-summarization)

### PR DESCRIPTION
**Pull request by MENNA123MAHMOUD**
resolves #278

### CODE REVIEW

**Comment by MENNA123MAHMOUD** [comment]
Implementing BLEU score lens for issue#323

**Comment by MENNA123MAHMOUD** [comment]
I published the bleu-score npm package and used it here.
The github repository for it is [here](https://github.com/MENNA123MAHMOUD/bleu-score)

**Comment by druzsan** [comment]
@MENNA123MAHMOUD meanwhile please consider fixing types (see Checks below).

**Comment by MENNA123MAHMOUD** [comment]
Hi @druzsan Is there a way to run some of these checks locally or automatically in the branch for faster iteration?

**Pull request closed without merging**
